// Generated by CoffeeScript 1.6.3
(function() {
  var googleConnect, start;
  start = function(utilities) {
    return googleConnect();
  };
  googleConnect = function() {
    var cfg, checkAuth, handleAuthResult;
    cfg = {
      id: '181733347279',
      apiKey: 'AIzaSyCLQdexpRph5rbV4L3V_9i0rXRRNiib304',
      scope: 'https://www.googleapis.com/auth/calendar'
    };
    $('body').append('<script src="https://apis.google.com/js/client.js?onload=handleClientLoad"></script>');
    window.handleClientLoad = function() {
      gapi.client.setApiKey(cfg.apiKey);
      return window.setTimeout(checkAuth, 1);
    };
    checkAuth = function() {
      return gapi.auth.authorize({
        client_id: cfg.id,
        scope: cfg.scope,
        immediate: true
      }, handleAuthResult);
    };
    return handleAuthResult = function() {
      return alert(1);
    };
  };
  return {
    start: start
  };
});
