// Generated by CoffeeScript 1.7.1
(function() {
  var drawExportButton, exportCompanyData, formFieldsByNames, formHost, formPath, getGeneralInfoFields, getVariousFields, resultsTableUrl, start, taistApi;
  taistApi = null;
  start = function(_taistApi, entryPoint) {
    taistApi = _taistApi;
    taistApi.haltOnError = true;
    switch (entryPoint) {
      case 'companyPage':
        return drawExportButton();
    }
  };
  drawExportButton = function() {
    var exportButton, previousButtonClass, successMessage;
    previousButtonClass = 'follow_button';
    exportButton = jQuery('<input />', {
      title: 'Export',
      value: 'Export',
      type: 'submit',
      "class": previousButtonClass + " exportButton",
      click: function() {
        successMessage.hide();
        exportCompanyData(function() {
          return successMessage.show(300);
        });
        return false;
      }
    });
    (jQuery('.' + previousButtonClass)).after(exportButton);
    successMessage = jQuery("<a href=\"" + resultsTableUrl + "\" target=\"_blank\">succeeded</a>");
    exportButton.after(successMessage);
    return successMessage.hide();
  };
  exportCompanyData = function(callback) {
    var exportedData, fieldValuesByNames, formField, name;
    fieldValuesByNames = jQuery.extend(getGeneralInfoFields(), getVariousFields());
    exportedData = {};
    for (name in formFieldsByNames) {
      formField = formFieldsByNames[name];
      exportedData[formField] = fieldValuesByNames[name];
    }
    return taistApi.proxy.jQueryAjax(formHost, formPath, {
      type: 'POST',
      data: exportedData
    }, function() {
      return callback();
    });
  };
  getGeneralInfoFields = function() {
    var addFieldValue, attrName, fieldName, fieldValues, firstElementValueFields, textValueFields, _i, _len;
    textValueFields = ['twitter', 'category', 'phone', 'founded', 'description'];
    firstElementValueFields = {
      'website': 'href',
      'blog': 'href',
      'email': 'title'
    };
    fieldValues = {};
    addFieldValue = function(fieldName, valueExtractor) {
      var caption, captions, targetCaptionCell, valueCell, _i, _len, _results;
      captions = jQuery(".col1_content:first .td_left");
      _results = [];
      for (_i = 0, _len = captions.length; _i < _len; _i++) {
        caption = captions[_i];
        if (!(caption.textContent.toLowerCase() === fieldName)) {
          continue;
        }
        targetCaptionCell = jQuery(caption);
        valueCell = targetCaptionCell.next();
        fieldValues[fieldName] = valueExtractor(valueCell);
        break;
      }
      return _results;
    };
    for (_i = 0, _len = textValueFields.length; _i < _len; _i++) {
      fieldName = textValueFields[_i];
      addFieldValue(fieldName, function(valueCell) {
        return valueCell.text();
      });
    }
    for (fieldName in firstElementValueFields) {
      attrName = firstElementValueFields[fieldName];
      addFieldValue(fieldName, function(valueCell) {
        return valueCell.children('a').attr(attrName);
      });
    }
    return fieldValues;
  };
  getVariousFields = function() {
    var fieldName, fieldValues, selector, _ref;
    fieldValues = {};
    _ref = {
      name: '#breadcrumbs span:last',
      funding_total: '.col1_funding_round_total .td_right2',
      employees: '#num_employees',
      tags: jQuery('a[href^="/tag/"]').parent()
    };
    for (fieldName in _ref) {
      selector = _ref[fieldName];
      fieldValues[fieldName] = (jQuery(selector)).text();
    }
    return fieldValues;
  };
  formFieldsByNames = {
    name: 'entry.1943171209',
    funding_total: 'entry.1045338686',
    tags: 'entry.463063990',
    website: 'entry.1221589467',
    blog: 'entry.735195729',
    twitter: 'entry.1396754322',
    category: 'entry.2054180868',
    phone: 'entry.570035841',
    email: 'entry.1028216727',
    employees: 'entry.1818327023',
    founded: 'entry.13262189',
    description: 'entry.1053914929'
  };
  formHost = 'https://docs.google.com';
  formPath = '/forms/d/1Gh6uJXP7KyYqeEOe-zQAekBZfDFdt6g22a9aQ5zxL-M/formResponse';
  resultsTableUrl = 'https://docs.google.com/a/tai.st/spreadsheet/ccc?key=0At6Ryl-W8CwadHRhTU5TcjRUcEtFb0dpQWRxV0ZvTHc&usp=drive_web#gid=0';
  return {
    start: start
  };
});
